### ISSUE TITLE
Intersect-Problem

### ISSUE THREAD

**Issue by DerElJoNo** [DerElJoNo/Joppa#3]
How can I check intersections with (/ distance to) other objects, based on the size of its picture?
@apricote ,der Issue hat übrigens keine Eile, bevor das Literatur-Projekt nicht fertig ist, brauchst du das hier nicht machen. Ich weiß, dass du damit noch viel zu tun hast.

**Comment by apricote** [comment]
Actor.getIntersectingObjects(java.lang.Class cls)?
